=== toschill/EBUT/DTD Lab 1 Produktkatalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % preis "(Steuer, W채hrung, Betrag, Land)">
<!ELEMENT Produktkatalog (Header, Artikel+)>
<!ELEMENT Header (Beschreibung?, GenDatum, ErzeugerName)>
<!ELEMENT Beschreibung (#PCDATA)>
<!ELEMENT GenDatum (#PCDATA)>
<!ELEMENT ErzeugerName (#PCDATA)>
<!ELEMENT Artikel (kurzeBeschreibung, Hersteller?, langeBeschreibung?, Preise, sonstigeNummer*)>
<!ATTLIST Artikel
	ArtikelNr ID #REQUIRED
	Zubehoer IDREFS #IMPLIED
>
<!ELEMENT kurzeBeschreibung (#PCDATA)>
<!ELEMENT Hersteller (#PCDATA)>
<!ELEMENT langeBeschreibung (#PCDATA | wichtig)*>
<!ELEMENT wichtig (#PCDATA)>
<!ELEMENT Preise (Netto+ | Brutto+)>
<!ELEMENT sonstigeNummer (Art, Nummer)*>
<!ELEMENT Art (#PCDATA)>
<!ELEMENT Nummer (#PCDATA)>
<!ELEMENT Netto (%preis;)>
<!ELEMENT Brutto (%preis;)>
<!ELEMENT Steuer (#PCDATA)>
<!ELEMENT W채hrung EMPTY>
<!ATTLIST W채hrung
	w채hrung (EUR | USD | CHF | GBP) "EUR"
>
<!ELEMENT Betrag (#PCDATA)>
<!ELEMENT Land (#PCDATA)>

=== toschill/EBUT/XML Lab 1 Produktkatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Produktkatalog SYSTEM "Z:\EBUT\DTD Lab 1 Produktkatalog.dtd">
<Produktkatalog>
	<Header>
		<Beschreibung>Testzweck</Beschreibung>
		<GenDatum>14.10.2014</GenDatum>
		<ErzeugerName>dosickel</ErzeugerName>
	</Header>
	<Artikel ArtikelNr="a234">
		<kurzeBeschreibung>testArtikel1</kurzeBeschreibung>
		<Preise>
			<Netto>
				<Steuer>2%</Steuer>
				<Währung währung="CHF"></Währung>
				<Betrag>20</Betrag>
				<Land>DE</Land>
			</Netto>
			<Netto>
				<Steuer>5%</Steuer>
				<Währung></Währung>
				<Betrag>40</Betrag>
				<Land>DE</Land>
			</Netto>
		</Preise>
		<sonstigeNummer>
			<Art>EAN</Art>
			<Nummer>4321</Nummer>
		</sonstigeNummer>
		<sonstigeNummer>
			<Art>UPC</Art>
			<Nummer>4567</Nummer>
		</sonstigeNummer>
	</Artikel>
	<Artikel ArtikelNr="a235">
		<kurzeBeschreibung>testArtikel2</kurzeBeschreibung>
		<Preise>
			<Netto>
				<Steuer>2%</Steuer>
				<Währung währung="USD"></Währung>
				<Betrag>20</Betrag>
				<Land>DE</Land>
			</Netto>
			<Netto>
				<Steuer>5%</Steuer>
				<Währung></Währung>
				<Betrag>40</Betrag>
				<Land>DE</Land>
			</Netto>
		</Preise>
		<sonstigeNummer>
			<Art>EAN</Art>
			<Nummer>4321</Nummer>
		</sonstigeNummer>
		<sonstigeNummer>
			<Art>UPC</Art>
			<Nummer>4567</Nummer>
		</sonstigeNummer>
	</Artikel>
	<Artikel ArtikelNr="a532" Zubehoer="a234 a235 a532">
		<kurzeBeschreibung>testArtikel3</kurzeBeschreibung>
		<Preise>
			<Brutto>
				<Steuer>7%</Steuer>
				<Währung währung="USD"></Währung>
				<Betrag>35</Betrag>
				<Land>USA</Land>
			</Brutto>
			<Brutto>
				<Steuer>10%</Steuer>
				<Währung></Währung>
				<Betrag>200</Betrag>
				<Land>DE</Land>
			</Brutto>
		</Preise>
		<sonstigeNummer>
			<Art>EAN</Art>
			<Nummer>4321</Nummer>
		</sonstigeNummer>
		<sonstigeNummer>
			<Art>UPC</Art>
			<Nummer>4567</Nummer>
		</sonstigeNummer>
	</Artikel>
</Produktkatalog>
